FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY /ServiceAPIGateway/target/ServiceAPIGateway-0.0.1-SNAPSHOT.jar /opt/lib/
COPY ServiceAPIGateway-entrypoint.sh /opt/bin/ServiceAPIGateway-entrypoint.sh
RUN chmod 755 /opt/bin/ServiceAPIGateway-entrypoint.sh
EXPOSE 8765