FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY /outreachmanagementapi/target/outreachmanagementapi-0.0.1-SNAPSHOT.jar /opt/lib/
COPY Outreachmment-entrypoint.sh /opt/bin/Outreachmment-entrypoint.sh
RUN chmod 755 /opt/bin/Outreachmment-entrypoint.sh
EXPOSE 8083
