FROM alpine-jdk:base
MAINTAINER javaonfly
RUN apk --no-cache add netcat-openbsd
COPY /Auth-Service/target/Auth-Service-0.0.1-SNAPSHOT.jar /opt/lib/
COPY UserAuthentication-entrypoint.sh /opt/bin/UserAuthentication-entrypoint.sh
RUN chmod 755 /opt/bin/UserAuthentication-entrypoint.sh
EXPOSE 9300