FROM alpine-jdk:base
MAINTAINER javaonfly
COPY /ServiceRegistration/target/ServiceRegistration-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/ServiceRegistration-0.0.1-SNAPSHOT.jar"]
EXPOSE 8761